### PR TITLE
fix(blogList): Fix next page url bug in blogs page

### LINKED ISSUE #322: [BUG] The "next page" button in blog-list page is not working
**Describe the bug**
Screen Shot 2020-06-27 at 10 56 07 PM

**To Reproduce**
URL or Steps to reproduce the behavior:
1. Go to Blogs page
2. Click on "Next Page" and you'll see the error

**Expected behavior**
Should show the next page

**Screenshots**

**Optional: Desktop (please complete the following information):**

**Optional: Smartphone (please complete the following information):**

### PR DESCRIPTION
**Pull request by misunchoi**
## Proposed changes
This is a temporary solution to grab the next page from the `http://backend:8000/api/v1/blogpostcontent/?page=2` url. A better solution would be to have the backend send just the `page=` parameter, but not sure how much time that'll take to fix it.

image (1)

## Types of changes

- [x] I've labeled this PR with appropriate labels (`comp/*` component, bug/feature, documentation and other less important ones).

## Checklist
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. This is simply a reminder of what we are going to look for before merging your code._

- [x] I've linked the proper Github Issue(s) to my PR
closes #322

### CODE REVIEW

File: frontend/src/pages/BlogSearchResults/BlogListPage.jsx [hunk 1]
```diff
@@ -199,7 +198,7 @@ const BlogSearch = ({ term }) => {
       </Section>
 
       <Section>
-        {isLoading || searchResults === null ? (
+        {isLoading ? (
```
Comment (jessewoo) [inline frontend/src/pages/BlogSearchResults/BlogListPage.jsx:201]: I think I added this because search results could be null - on the initiate load. There is like a glitch if you don't add in this condition.

Comment (misunchoi) [reply frontend/src/pages/BlogSearchResults/BlogListPage.jsx:201]: oh I see, yeah I can revert this change - I removed it cuz it wasn't showing the error when it was giving 503 errors from the backend, so the spinner was always showing without any indication that there was an error
